# Generated by Django 4.1.4 on 2022-12-19 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topup_amount", models.PositiveIntegerField()),
                ("talktime", models.PositiveIntegerField()),
                ("validity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Recharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=14)),
                (
                    "type",
                    models.CharField(
                        choices=[("PREPAID", "PREPAID"), ("POSTPAID", "POSTPAID")],
                        max_length=10,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[("PREPAID", "PREPAID"), ("POSTPAID", "POSTPAID")],
                        max_length=15,
                    ),
                ),
                (
                    "circle",
                    models.CharField(
                        choices=[("PREPAID", "PREPAID"), ("POSTPAID", "POSTPAID")],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recharge.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
