# Generated by Django 4.1.4 on 2022-12-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan", options={"ordering": ["topup_amount"]},
        ),
        migrations.AlterField(
            model_name="plan", name="validity", field=models.IntegerField(default=30),
        ),
    ]
