# Generated by Django 4.1.4 on 2022-12-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0002_alter_plan_options_alter_plan_validity"),
    ]

    operations = [
        migrations.AlterModelOptions(name="plan", options={},),
    ]
