# Generated by Django 4.1.4 on 2022-12-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0003_alter_plan_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan", options={"ordering": ["topup_amount"]},
        ),
    ]
