# Generated by Django 4.1.4 on 2022-12-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0004_alter_plan_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recharge",
            name="circle",
            field=models.CharField(
                choices=[
                    ("MUMBAI", "MUMBAI"),
                    ("DELHI", "DELHI"),
                    ("GUJARAT", "GUJARAT"),
                    ("HARYANA", "HARYANA"),
                    ("KOLKATA", "KOLKATA"),
                    ("PUNJAB", "PUNJAB"),
                    ("RAJASTHAN", "RAJASTHAN"),
                    ("TAMILNADU", "TAMILNADU"),
                    ("KERALA", "KERALA"),
                    ("JAMMU AND KASHMIR", "JAMMU AND KASHMIR"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="operator",
            field=models.CharField(
                choices=[
                    ("RELIANCE", "RELIANCE"),
                    ("TATA DOCOMO", "TATA DOCOMO"),
                    ("VODAFONE", "VODAFONE"),
                    ("IDEA", "IDEA"),
                    ("MTNL", "MTNL"),
                    ("AIRCEL", "AIRCEL"),
                    ("AIRTEL", "AIRTEL"),
                    ("MTS", "MTS"),
                ],
                max_length=15,
            ),
        ),
    ]
