# Generated by Django 4.1.4 on 2022-12-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0005_alter_recharge_circle_alter_recharge_operator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan", old_name="validity", new_name="validity_in_days",
        ),
        migrations.AlterField(
            model_name="recharge",
            name="circle",
            field=models.CharField(
                choices=[
                    ("MAHARASHTRA & GOA", "MAHARASHTRA & GOA"),
                    ("DELHI", "DELHI"),
                    ("GUJARAT", "GUJARAT"),
                    ("HARYANA", "HARYANA"),
                    ("KOLKATA", "KOLKATA"),
                    ("PUNJAB", "PUNJAB"),
                    ("RAJASTHAN", "RAJASTHAN"),
                    ("TAMILNADU", "TAMILNADU"),
                    ("KERALA", "KERALA"),
                    ("JAMMU AND KASHMIR", "JAMMU AND KASHMIR"),
                ],
                max_length=20,
            ),
        ),
    ]
