# Generated by Django 4.1.4 on 2022-12-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_wallet_debitcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debitcard",
            name="expiration_date",
            field=models.CharField(max_length=6),
        ),
    ]
